services:
  app:
    build: .
    container_name: vacation_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=vacation_db
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=Redlabel@
      - DB_NAME=vacation_system
      - GOOGLE_CLIENT_ID=965044613148-re34p879kimc8msr3hr74mnqdlidvb3l.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - MAIL_USERNAME=afernandezl@uandina.edu.pe
      - MAIL_PASSWORD=rgpm hlka jdxr ryjn
      - MAIL_FROM=afernandezl@uandina.edu.pe
      - MAIL_PORT=587
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_FROM_NAME=RRHH UAndina
      - MAIL_STARTTLS=True
      - MAIL_SSL_TLS=False
    depends_on:
      vacation_db:
        condition: service_healthy
    
    # --- AÑADE ESTAS DOS LÍNEAS ---
    volumes:
      - .:/app
    # --- FIN DE LA MODIFICACIÓN ---
    
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  vacation_db:
    image: mysql:8.0
    container_name: vacation_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Redlabel@
      MYSQL_DATABASE: vacation_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: Redlabel@
    volumes:
      - vacation_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "admin", "-pRedlabel@"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  vacation_mysql_data: